config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  devise_scope :user do
    authenticated :user do
      root :to => "categories#index", as: :authenticated_root
    end
    unauthenticated :user do
      root :to => "home#index", as: :unauthenticated_root
    end
  end

  resources :categories, only: [:index,:show,:new,:create]
  resources :payments, only: [:index,:new,:create]
end

app/views/shared/_card.html.erb
<%= link_to category_path(category)  do %>
<div class="bg-white w-full h-40 grid grid-cols-4 gap-2 p-3 my-2">
    <div class="w-full col-span-1 h-full flex items-center">
        <%= image_tag category.icon %>
    </div>
    <div class="col-span-3 flex flex-col justify-around py-5">
        <div class="flex justify-between w-full">
            <span class="text-main-300"><%= category.name %> </span>
            <span class="text-main-300">$ <%= Payment.total_amounts(category.payments)%></span>
        </div>
        <div class="text-main-300"  >
        <%= category.created_at %>
        </div>
    </div>
</div>
<%end%>

app/views/shared/_card_category.html.erb
<%= link_to category_path(category)  do %>
<div class="bg-white w-full grid grid-cols-4 gap-2 p-3 my-2">
    <div class="w-full col-span-1 h-[100px] flex items-center object-cover">
        <%= image_tag category.icon %>
    </div>
    <div class="col-span-3 flex flex-col justify-around py-5">
        <div class="flex justify-between w-full">
            <span class="text-main-300"><%= category.name %> </span>
            <span class="text-main-300">$ <%= Payment.total_amounts(category.payments)%></span>
        </div>
        <div class="text-main-300"  >
        <%= category.created_at %>
        </div>
    </div>
</div>
<%end%>

app/views/shared/_card_show.html.erb
<div class="bg-white w-full p-3 my-2 h-[320px]">
    <div class="grid grid-cols-4 gap-6 border-b-2 border-slate-200 pb-4">
        <div class="w-full col-span-1 h-[100px] flex items-center object-cover">
            <%= image_tag payment.category.icon %>
        </div>
        <div class="col-span-3 h-full items-center text-3xl text-main-300 flex py-5">
            <p><%=payment.name%></p>
        </div>
    </div>
    <div class="flex flex-col py-5 text-main-300 border-b-2 border-slate-200 ">
        <p>Created By: <%= payment.user.name%> </p>
        <p>Created at: <%= payment.created_at%> </p>
    </div>
    <div class="flex w-full justify-between items-center px-2 text-main-300 py-5 text-3xl">
        <span>Total Payment</span>
        <span>$ <%= payment.amount%></span>
    </div>
</div>

app/views/shared/_flash.html.erb
<% flash.each do |type, msg| %>
  <% if type == 'alert' %>
  <div class="py-5 text-center rounded-md text-white bg-yellow-400" >
    <%= msg %>
  </div>
  <% else %>
  <div class="py-5 text-center rounded-md text-white bg-main-200">
    <%= msg %>
  </div>
  <% end %>
<% end %>

app/views/shared/_header.html.erb
<header class="flex justify-between items-center px-2 bg-main-100 py-5">
    <div class="w-10 text-white">
        <%= link_to image_tag(image) ,target_link%>
    </div>

    <div class="text-white text-3xl">
        <span><%=title%></span>
    </div>
    <div class="flex items-center text-white">
        <%= link_to image_tag('cate.png') ,categories_path%>
        <%= link_to image_tag('pay.png') ,payments_path%>
    </div>
</header>