config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  devise_scope :user do
    authenticated :user do
      root :to => "categories#index", as: :authenticated_root
    end
    unauthenticated :user do
      root :to => "home#index", as: :unauthenticated_root
    end
  end

  resources :categories, only: [:index,:show,:new,:create]
  resources :payments, only: [:index,:new,:create]
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user, foreign_key: 'author_id', class_name: 'User'
  has_many :payments, dependent: :destroy

  validates :name, presence: true, length: { minimum: 5, maximum: 50 }
  validates :icon, presence: true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!

  def index
    @categories = current_user.categories
  end

  def new
    @category = Category.new
  end

  def create
    @category = current_user.categories.new(categories_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_path, notice: 'category added successfully' }
      else
        format.html { render :new, notice: 'something went wrong, please try again' }
      end
    end
  end

  def show
    @category = Category.includes(:payments).order('created_at DESC').find(params[:id])
  end

  private

  def categories_params
    params.require(:category).permit(:name, :icon)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/index.html.erb
<div>
  <%= render 'shared/header',title:'Categories',image:'',target_link: ''%>
  <%= render 'shared/flash'%>
  <div class="flex flex-col overflow-scroll h-[75vh]">
    <% if @categories.empty? %>
    <div>
      <p> No Categories Added</p>
    </div>
    <% else %>
    <div class="p-4">
      <% @categories.each do |category| %>
      <%= render "shared/card_category", category: category %>
      <%end%>
    </div>
    <%end%>
  </div>
  <div>
  <%= link_to new_category_path do%>
  <div class="w-screen flex justify-center fixed bottom-0 bg-main-200 p-4 hover:cursor-pointer">
  <div class="h-20 flex justify-center items-center p-4  bg-main-200 text-white w-fit text-3xl border-2 border-white">
  <p>Add Category</p>
  </div>
  </div>
  <%end%>
</div>

app/views/categories/new.html.erb
  <%= render 'shared/header',title:'Categories',image:'back.svg',target_link: categories_path%>

  <div class="flex flex-col w-screen h-full ">
      <%= form_with model: @category, method: :post, local: true do |f| %>
      <div class="h-2/4 justify-center items-center mt-32">
          <div class="flex flex-col text-main-300 px-4">
              <%= f.label :Name%>
              <%= f.text_field :name, required: true, placeholder: "Category Name" %>
          </div>
          <div class="flex flex-col text-main-300 px-4 mt-11">
              <%= f.label :Icon%>
              <%= f.text_field :icon, required: true, placeholder: "Category Icon"%>
          </div>
      </div>
      <div class="w-screen flex justify-center fixed bottom-0 bg-main-200 p-4 hover:cursor-pointer">
          <div
              class="h-20 flex justify-center items-center p-4  bg-main-200 text-white w-fit text-3xl border-2 border-white">
              <%= f.submit "Save" %>
          </div>
      </div>
      <% end %>
  </div>

app/views/categories/show.html.erb
  <%= render 'shared/header',title:'Categories',image:'back.svg',target_link: categories_path%>
  <div class="flex justify-between bg-white p-5 text-main-300 text-2xl">
      <span>Total payments</span>
      <span>$ <%= Payment.total_amounts(@category.payments)%></span>
  </div>

  <div class="p-4 h-full bg-slate-100">
      <% if @category.payments.empty? %>
      <p> No Payments Added Yet</p>
      <%else%>
      <% @category.payments.each do |payment|%>
      <%= render "shared/card_show", payment: payment %>
      <%end%>
      <%end%>
      <%= link_to new_payment_path do%>
      <div class="w-screen flex justify-center fixed bottom-0 bg-main-200 p-4 hover:cursor-pointer">
          <div
              class="h-20 flex justify-center items-center p-4  bg-main-200 text-white w-fit text-3xl border-2 border-white">
              <p>Add Payment</p>
          </div>
      </div>
      <%end%>
  </div>